name : Foundation5/github pages/Jykill starter
brand : Laboratory for Cellular Biophysics
description : Lab webpage
keyword : 
url : http://arpitalab.github.io/labpage1
email : arpitau@umd.edu
twitter : DaigoFuji
github : arpitalab
author : Arpita Upadhyaya
year : 2016
markdown : kramdown
exclude :
  - node_modules
